WeddingManagerSite/InvitationManager/urls.py
from django.urls import path
from django.contrib.admin.views.decorators import staff_member_required

from . import views

app_name="InvitationManager"

urlpatterns = [
	path('', views.index, name='index'),
	# path('yourinvitation/<str:invitation_id>', views.invitation_endpoint, name='invitation_endpoint'),
	path('yourinvitation/<str:invitation_id>', views.InvitationHomepage.as_view(), name='invitation_endpoint'),
	path('yourinvitation/', views.missing_invitation, name='invalid_invitation_endpoint'),
	path("import/", views.ImportGuestsView.as_view(), name="db_import_endpoint"),
	path("help/", views.help_page, name="help"),
	path("yourinvitation/rsvp/<str:invitation_id>", views.RSVPFormView.as_view(), name="rsvp"),
	path("location", views.location_page, name="location"),
	path("contact", views.contact_us_page, name="contact_us"),
	path("info", views.info_page, name="info"),

	# path('media/<str:media_name>', 'django.views.static.serve', { 'document_root': settings.MEDIA_ROOT })
]

WeddingManagerSite/WeddingManagerSite/urls.py
from django.contrib import admin
from django.urls import path, include
# import views

urlpatterns = [
	path("", include("InvitationManager.urls", namespace="InvitationManager")),
	path('admin/', admin.site.urls),
]

WeddingManagerSite/InvitationManager/forms.py
from django import forms
from .models import Guest, Group, RSVP, Invitation
from .enums import DisplayStrings

class ImportGuestsForm(forms.Form):
	CLEAR_DB_CHOICES = [
		("True", "Clear DB"),
		("False", "Keep DB")
	]
	file_upload = forms.FileField(label="file_upload")
	clear_db = forms.CharField(
		label="Clear DB?",
		widget=forms.RadioSelect(choices=CLEAR_DB_CHOICES)
	)

class RSVPForm(forms.ModelForm):


	class Meta:
		model = RSVP
		fields = ["is_attending", "is_vegan", "is_attending_ceremony"]


class RSVPSubform(forms.ModelForm):
	ATTENDANCE_OPTIONS = [
		(True, DisplayStrings.IS_ATTENDING),
		(False, DisplayStrings.IS_NOT_ATTENDING)
	]
	parent_invitation = None
	is_attending = forms.ChoiceField(choices=ATTENDANCE_OPTIONS, widget=forms.RadioSelect)
	is_vegan = forms.CheckboxInput()

	class Meta:
		model = RSVP
		exclude = ("rsvp_id",)
	
	def get_all_guests(self):
		return Guest.objects.filter(assoc_invitation=self.parent_invitation)

WeddingManagerSite/InvitationManager/views.py
import csv
from datetime import datetime
import logging
from xmlrpc.client import SERVER_ERROR

from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators import login_required
from django.core import exceptions as django_exceptions
from django.http import HttpResponse, HttpResponseRedirect
from django.http.response import HttpResponseBadRequest, HttpResponseServerError
from django.shortcuts import render
from django.utils.decorators import method_decorator
from django.views.generic import View
from django.http.request import HttpRequest
from django.shortcuts import redirect

from InvitationManager import event_details

from . import models as InvitationModels
from .forms import ImportGuestsForm, RSVPSubform
import pytz
from django.utils import timezone

def get_invitation_by_url_id(url_id) -> InvitationModels.Invitation:
		"""
		Gets the Invitation object associated with this URL ID.
		If there is no Invitation associated with this URL, raises ObjectDoesNotExist exception.

		Args:
			url_id (str): URL ID of the invitation. Should come from InvitationModels.Invitation.invitation_url_id.

		Raises:
			django_exceptions.ObjectDoesNotExist: Raised if no Invitation was found for this URL ID.

		Returns:
			InvitationModels.Invitation: The invitation associated with this URL ID.
		"""

		try:
			invitation = InvitationModels.Invitation.objects.get(invitation_url_id=url_id)
			if invitation is None:
				raise django_exceptions.ObjectDoesNotExist()
			return invitation
		# This is raised when the url_id does not match a single invitation.
		except django_exceptions.ObjectDoesNotExist as no_inv_error:
			print("Invitation could not be found!")
			InvitationModels.LogEvent.log_get_invitation_by_url_id(
				"error",
				"func_call",
				f"URL ID could not be found: {url_id}",
				None
			)
			raise no_inv_error
		except Exception as err:
			print(str(err))

def index(request):
	return render(request, "InvitationManager/missing_invitation.html")

def help_page(request):
	context = {}
	if "invitation_url_id" in request.session:
		context["invitation_url_id"] = request.session["invitation_url_id"]
	InvitationModels.LogEvent.log_help_page_visit(
		"info",
		"page_visit",
		"Help page",
		None if "invitation_url_id" not in context else get_invitation_by_url_id(context["invitation_url_id"])
	)

	return render(request, "InvitationManager/help.html", context)

def missing_invitation(request):
	InvitationModels.LogEvent.log(
		"info",
		"page_visit",
		"Missing invitation page",
		None
	)
	return render(request, "InvitationManager/missing_invitation.html")

def location_page(request: HttpRequest):
	from .event_details import EventDetails
	details = EventDetails()
	context = {
		"venue_name": details.venue_name,
		"venue_addr": details.venue_address,
		"google_embed_url": details.venue_map_embed_link,
		"google_link": details.venue_google_link
	}
	if "invitation_url_id" in request.session:
		context["invitation_url_id"] = request.session["invitation_url_id"]
	
	InvitationModels.LogEvent.log_location_page_visit(
		"info",
		"page_visit",
		"Location page",
		context["invitation_url_id"] if "invitation_url_id" in context else None
	)
	return render(request, "InvitationManager/location.html", context)

def contact_us_page(request: HttpRequest):
	from .event_details import EventDetails
	details = EventDetails()
	context = {
		"help_phone": details.help_phone,
		"help_phone_formatted": "-".join([
			details.help_phone[:3],
			details.help_phone[3:6],
			details.help_phone[6:]
		]),
		"help_email": details.help_email
	}
	invitation_url_id = None
	if "invitation_url_id" in request.session:
		context["invitation_url_id"] = request.session["invitation_url_id"]
		invitation_url_id = request.session["invitation_url_id"]
	InvitationModels.LogEvent.log_contact_us_page_visit(
		"info",
		"page_visit",
		"Contact us page",
		invitation_url_id
	)
	return render(request, "InvitationManager/contact_us.html", context)

def info_page(request: HttpRequest):
	from .event_details import EventDetails
	details = EventDetails()
	ceremony_tstamp: datetime = details.ceremony_timestamp
	context = {
		"wedding_date_formatted": "{dt:%B} {dt.day}, {dt.year}".format(dt=details.ceremony_timestamp),
		"ceremony_time_formatted": "{hr}:{dt:%M} {m}".format(
			dt=details.ceremony_timestamp, 
			hr=event_details.hour24_as_hour12(details.ceremony_timestamp.hour),
			m='AM' if details.ceremony_timestamp.hour < 12 else 'PM'
		),
		"ceremony_location": details.ceremony_location_name,
		"reception_time_formatted": "{hr}:{dt:%M} {m}".format(
			dt=details.reception_timestamp, 
			hr=event_details.hour24_as_hour12(details.reception_timestamp.hour),
			m='AM' if details.reception_timestamp.hour < 12 else 'PM'
		),
		"reception_location": details.reception_location_name,
		"hotel_name": details.hotel_name,
		"hotel_url": details.hotel_url
	}
	if "invitation_url_id" in request.session:
		context["invitation_url_id"] = request.session["invitation_url_id"]
	InvitationModels.LogEvent.log_info_page_visit(
		"info",
		"page_visit",
		"Info page",
		context["invitation_url_id"] if "invitation_url_id" in context else None
	)
	return render(request, "InvitationManager/event_info.html", context)

@method_decorator(staff_member_required, name="dispatch")
class ImportGuestsView(View):
	"""
	View for importing guests into the database.
	"""

	def get(self, request):
		form = ImportGuestsForm()
		return render(request, "InvitationManager/import_page.html", {"form": form})

	def post(self, request):
		import WeddingManagerSite.db as AppDatabase
		form = ImportGuestsForm(request.POST, request.FILES)
		if form.is_valid():
			# // if form clear_db is checked, delete all guests
			if "clear_db" in form.cleaned_data and form.cleaned_data["clear_db"] == "True":
				backed_up = AppDatabase.backup_db()
				if backed_up:
					# InvitationModels.Guest.objects.all().delete()
					print("DB cleared")
					self.handle_input_file(request.FILES["file_upload"])
			# // handle_input_file(request.FILES["file_upload"])
			return HttpResponse("<html><h1>Import Successful</h1></html>")
		else:
			return HttpResponse("<html><h1>Import FAILED<br><a href=''</h1></html>")
	
	def handle_input_file(self, file_obj):
		"""
		Handles CSV input for database import.

		1. Reads the csv data line by line or chunk by chunk.
		2. Creates SQL queries for each line that will be executed as the file is read.
			- Consider using transactions that only get applied after all rows have been successfully read.
			- Only insert into the database if ALL rows in the CSV are confirmed valid.

		Please note, some fields are foreign keys. Meaning you cannot assign them a value.
		Instead, you must create/find the relevant model for the foreign key.
		For example: Guest requires an assoc_group foreign key.
			- This can be satisfied by searching for the group by its primary key (group_label)
				or by creating a new group.
			- The following links will be relevant to getting this done.
				https://docs.djangoproject.com/en/3.2/ref/models/querysets/#get
				https://docs.djangoproject.com/en/3.2/ref/models/querysets/#get-or-create

		Heres an example of how to insert into the database.
		This will create the guest Bob Belcher and fill in his information.
		Notice the foreign keys `relation` and `assoc_group` use Django SQL queries to acquire the foreign key.
		InvitationModels.Guest(
			first_name="Bob",
			last_name="Belcher",
			relation=InvitationModels.Guest_Relation.objects.get(relation_en="Father"),
			whose_guest=InvitationModels.Guest.WHOSE_GUEST_OPTION_DICT["PETER"][0],
			home_address="123 Wharftown",
			phone_number=None,
			email="bob_burger@bobsburgers.yum",
			fb_link=None,
			assoc_group=InvitationModels.Group.objects.get_or_create(group_label="The Belcher Family"),
			is_overseas=False,
			assoc_invitation=None,
			is_attending=None
		)
		Once all objects have been created, ensure it is valid by using the full_clean method.
		https://docs.djangoproject.com/en/3.2/ref/models/instances/#django.db.models.Model.full_clean
		If the object is not valid, itll raise a ValidationError to let you know.
		Handle this exception as is necessary to solve the problem.
		
		Once all objects are valid, go through and call the save() funciton on all of them.
		Note the code in this part of the Django tutorial.
		https://docs.djangoproject.com/en/3.2/intro/tutorial02/#playing-with-the-api

		Args:
			file_obj (InMemoryUploadedFile): In memory file object handling the CSV input.
		
		"""


		# This code takes the file-like object file_obj, creates a csv reader, then prints each row.
		# csv.DictReader: https://docs.python.org/3/library/csv.html#csv.DictReader
		# InMemoryUploadedFile: https://docs.djangoproject.com/en/3.0/_modules/django/core/files/uploadedfile/
		# csv_reader = csv.DictReader(file_obj)
		print("CSV Reader: ")


class InvitationHomepage(View):
	class HomepageButtonOptions():
		"""
		An enum class that represents the possible options a user can choose on the invitation homepage.
		"""
		FILL_INVITATION = 0
		REJECT_INVITATION = 1

		@staticmethod
		def as_str(option_code):
			"""
			Returns the string version of the code used. Useful for logging.

			Args:
				option_code (int): An integer option in the HomepageButtonOptions class.

			Raises:
				ValueError: Raised if an option code is inputted that does not exist.

			Returns:
				str: String version of code.
			"""

			if option_code == InvitationHomepage.HomepageButtonOptions.FILL_INVITATION:
				return "FILL_INVITATION"
			elif option_code == InvitationHomepage.HomepageButtonOptions.REJECT_INVITATION:
				return "REJECT_INVITATION"
			raise ValueError("Invitation option code not recognized.")

	def get(self, request: HttpRequest, invitation_id, *args, **kwargs):
		from .event_details import EventDetails

		invitation = None
		try:
			invitation = self.get_invitation_by_url_id(invitation_id)

WeddingManagerSite/InvitationManager/templates/InvitationManager/footer.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Document</title>
	<link rel="stylesheet" href="{% static " InvitationManager/css/styles.css" %}">
	<link rel="stylesheet" href="{% static " InvitationManager/css/footer.css" %}">
	<link rel="stylesheet"
		href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0" />
	<style type="text/css">
		{
			% comment %
		}

		.footerContainer {
			background-color: rgba(0, 0, 0, 0.5);
			display: flex;
		}

			{
			% endcomment %
		}

		.footerContainer {
			max-height: 30px;
			display: flex;
			align-items: center;
			background: unset;
			padding-bottom: 15px;
			justify-content: center;
		}

		.mailButton {
			background-color: rgb(93, 76, 89) !important;
			text-decoration: none !important;
			color: white !important;
			display: flex;
		}

		.mailButton:hover {
			box-shadow: inset 0 0 100px 100px rgba(255, 255, 255, 0.2);
		}
	</style>
</head>

<body>
	<div class="footerContainer">
		<!-- <span style="padding-right: 5px;">
			Need help? Email us
		</span> -->
		<button class="btn btn-light mailButton" onclick="location.href='{% url 'InvitationManager:contact_us' %}'">
			<span class="material-symbols-outlined" style="padding-right: 2px;">
				mail
			</span>
			Contact Us
		</button>
	</div>
</body>

</html>

WeddingManagerSite/InvitationManager/templates/InvitationManager/import_page.html
{% block title %}Guest Import{% endblock title %}
{% block content %}
<form method="post" enctype="multipart/form-data">
	{% csrf_token %}
	{{ form }}
	<input type="submit">
</form>
{% endblock content %}

WeddingManagerSite/InvitationManager/templates/InvitationManager/invitation_form.html
<form class="mb-5" method="post" id="contactForm" name="contactForm" novalidate="novalidate">
						<div class="row">
							<div class="col-md-12 form-group">
								<label for="name" class="col-form-label">Name</label>
								<input type="text" class="form-control" name="name" id="name">
							</div>
						</div>
						<div class="row">
							<div class="col-md-12 form-group">
								<label for="email" class="col-form-label">Email</label>
								<input type="text" class="form-control" name="email" id="email">
							</div>
						</div>
						<div class="row">
							<div class="col-md-12 form-group">
								<label for="message" class="col-form-label">Message</label>
								<textarea class="form-control" name="message" id="message" cols="30"
									rows="7"></textarea>
							</div>
						</div>
						<div class="row">
							<div class="col-md-12">
								<input type="submit" value="Send Message" class="btn btn-primary rounded-0 py-2 px-4">
								<span class="submitting"></span>
							</div>
						</div>
					</form>

WeddingManagerSite/InvitationManager/templates/InvitationManager/nav_bar.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Mea+Culpa&family=Parisienne&display=swap" rel="stylesheet">
	<style type="text/css">
		a,
		abbr,
		acronym,
		address,
		applet,
		b,
		big,
		blockquote,
		body,
		button,
		caption,
		center,
		cite,
		code,
		dd,
		del,
		dfn,
		div,
		dl,
		dt,
		em,
		fieldset,
		font,
		footer,
		form,
		h1,
		h2,
		h3,
		h4,
		h5,
		h6,
		header,
		html,
		i,
		iframe,
		img,
		ins,
		kbd,
		label,
		legend,
		li,
		nav,
		object,
		ol,
		p,
		pre,
		q,
		s,
		samp,
		section,
		small,
		span,
		strike,
		strong,
		sub,
		sup,
		table,
		tbody,
		td,
		tfoot,
		th,
		thead,
		title,
		tr,
		tt,
		u,
		ul,
		var {
			margin: 0;
			padding: 0;
			border: 0;
			outline: 0;
			vertical-align: baseline;
			background: transparent;
		}

		/* #siteHeader {
			position: relative;
			margin-top: 0;
			top: 0;
			padding-bottom: 5px;
			left: 0;
			margin-left: 0;
			width: 100%;
			min-width: 980px;
			z-index: 51;
			--above-all-in-container: 10000;
		} */

		#buttonContainer {
			display: flex;
			flex-direction: row;
			justify-content: center;
		}

		a .navButton {
			padding-left: 10px;
			padding-right: 10px;
		}

		/* .centering {
			position: relative;
			display: flex;
			flex-direction: column;
			margin: 0 auto;
			max-width: 980px;
			box-sizing: border-box;
			padding: 30px 68px;
			box-shadow: 0px 0px 10px 0px rgba(0, 0, 0, 0.5);
		} */
		.centering {
			width: 100%;
			padding-bottom: 20px;
		}

		.navbar {
			padding-left: 15vw;
			/* margin-bottom: 1.5em; */
		}

		.pntLogo {
			font: 500 normal normal 30px/1.4em 'Mea Culpa', cursive;
		}

		body {
			padding-top: 85px;
		}

		.bar {
			box-shadow: 0 0px 10px 0px rgb(0 0 0 / 50%);
		}
	</style>
</head>

<body>
	<nav class="navbar navbar-expand-sm navbar-light bg-light d-flex justify-content-around fixed-top bar">
		<!-- P&T Text Logo -->
		{% if invitation_url_id %}
		<a class="navbar-brand nav-link" href="{% url 'InvitationManager:invitation_endpoint' invitation_url_id %}">
		{% else %}
		<a class="navbar-brand nav-link" href="{% url 'InvitationManager:invalid_invitation_endpoint' %}">
		{% endif %}
			<p class="pntLogo">P&T</p></a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
			aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>

		<div class="collapse navbar-collapse" id="navbarSupportedContent">
			<ul class="navbar-nav mr-auto">
				{% if invitation_url_id %}
					<li class="nav-item">
						<a class="nav-link {% if 'invitation' in request.path_info %}active{% endif %}" href="{% url 'InvitationManager:invitation_endpoint' invitation_url_id %}">Your Invitation<span class="sr-only">(current)</span></a>
					</li>
				{% else %}
					<li class="nav-item">
						<a class="nav-link {% if 'invitation' in request.path_info %}active{% endif %}" href="{% url 'InvitationManager:invalid_invitation_endpoint' %}">Your Invitation<span class="sr-only">(current)</span></a>
					</li>
				{% endif %}
				
				<li class="nav-item">
					<a class="nav-link {% if 'info' in request.path_info %}active{% endif %}" href="{% url 'InvitationManager:info' %}">Info<span class="sr-only"></span></a>
				</li>
				<li class="nav-item">
					<a class="nav-link {% if 'location' in request.path_info %}active{% endif %}" href="{% url 'InvitationManager:location' %}">Where<span class="sr-only"></span></a>
				</li>
				<li class="nav-item">
					<a class="nav-link {% if 'help' in request.path_info %}active{% endif %}" href="{% url 'InvitationManager:help' %}">Help<span class="sr-only"></span></a>
				</li>
				<li class="nav-item">
					<a class="nav-link {% if 'contact' in request.path_info %}active{% endif %}" href="{% url 'InvitationManager:contact_us' %}">Contact Us<span class="sr-only"></span></a>
				</li>
				<!-- ADD MORE BUTTONS HERE -->
				<!-- <li class="nav-item">
					<a class="nav-link" href="#">Link</a>
				</li> -->
			</ul>
		</div>
	</nav>


	<!-- <div id="siteHeader" class="centering">
		<div id="buttonContainer">
			
		</div>
		</div> -->
</body>

WeddingManagerSite/InvitationManager/templates/InvitationManager/your_invitation.html
<!DOCTYPE html>
<html lang="en">

<head>
	{% block title %}<title>You're Invited</title>{% endblock %}
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<!-- Fonts -->
	<link href="https://fonts.googleapis.com/css2?family=Parisienne&display=swap" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css2?family=Mea+Culpa&family=Parisienne&display=swap" rel="stylesheet">
	<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css2?family=Charm&family=Mea+Culpa&family=Parisienne&display=swap"
		rel="stylesheet">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0" />

	<!-- Add additional CSS in static file -->
	{% load static %}
	<link rel="stylesheet" href="{% static 'css/styles.css' %}">
	<style type="text/css">
		.pntPageLogo {
			font: normal normal normal 3em/1.4em 'Mea Culpa', cursive;
			font-size: 5vh;
		}

		.fancyText {
			font: normal normal normal 1.2em/1.35em 'Charm', cursive;
			/* font-family: ; */
			text-align: center;
			font-size: 2.5vh;
			/* font-size: 2rem; */
		}
		

		.inviteeName {
			font-size: 1.4em;
			padding-top: 10px;
			padding-bottom: 10px;
			/* font-size: 2vw; */
		}

		.sectionDivider {
			padding-bottom: 0.5em;
		}

		.invBody {
			position: relative;
			display: flex;
			flex-direction: column;
			margin: 0 auto;
			max-width: 980px;
			box-sizing: border-box;
			/* // Box shadow only on left and right */
			width: 85%;
			padding-bottom: 20px;
		}

		.formContainerStyle {
			box-shadow: 0px 0px 10px 0px rgba(0, 0, 0, 0.5);
			padding: 30px;
			min-height: 85vh !important;
			min-height: 600px;
			display: flex;
			flex-direction: column;
			overflow: scroll;
		}


		.imgDivider {
			padding-top: 0.8em;
			padding-bottom: 0.8em;
			display: flex; 
			flex-direction: column; 
			align-items: center;
		}

		.imgDivider > img {
			/* width: 34px;
			height: 34px; */
			width: 5vh;
			height: 5vh;
		}

		.toRSVP {
			background-color: rgb(93, 76, 89) !important;
			width: 150px;
		}
		.toRSVP:hover {
			box-shadow: inset 0 0 100px 100px rgba(255, 255, 255, 0.2);
		}

		.toEventInfo {
			background-color: rgb(255, 255, 255) !important;
			border: 1px solid rgb(93, 76, 89);
			
			font-size: 2.5vh;
			color: rgb(93, 76, 89) !important; 
			
		}
		.toEventInfo:hover {
			box-shadow: inset 0 0 100px 100px rgba(255, 255, 255, 0.2);
		}

		.submitContainer {
			flex-grow: 1;
			justify-content: center;
		}

		.toRSVPLink {
			color: white !important; 
			text-decoration: none !important;
		}

		.pageContainer {
			max-height: 100vh;
			/* overflow: hidden; */
		}

	</style>
</head>

<body>

	<div class="pageContainer">

	<div>

		{% include "InvitationManager/nav_bar.html" %}
	</div>
	<div class="invBody d-flex flex-column h-100">
		<div class="formContainerStyle">
			<div class="d-flex flex-column align-items-center">
				<!-- <h1 class="mb-4 pntLogo">P | T</h1> -->
				<!-- <img src="http://127.0.0.1:8000/invitations/media/leaves.png"> -->
				<p class="pntPageLogo sectionDivider">P&T</p>
				
				<div>
					<div class="sectionDivider">
						<div class="fancyText">
							<p>{{ partner_1.first_name }} and {{ partner_2.first_name }} joyfully invite </p>
							<!-- <br>  -->
							<p class="fancyText inviteeName"> 
								{% if invitation_guests|length == 1 %}
									{{ invitation_guests.0 }}
								{% else %}
									{% for name in invitation_guests %}
										{% if forloop.last %}
											and <br>
											{{ name }} 
										{% elif forloop.revcounter == 2 %}
											{{ name }}<br>
										{% else %}
											{{ name }},<br>
										{% endif %}
									{% endfor %}
								{% endif %}
							</p>
							<!-- <br>  -->
							<p>to their wedding celebration</p>
						</div>
						
			<div class="imgDivider">
				<img src="https://i.imgur.com/bJ0ZU1o.png">
			</div>
							<p class="fancyText">{{ wedding_date }}</p>
						<!-- <p class="fancyText">{{ wedding_time }}</p> -->
					</div>
					<div>
						<p class="fancyText">Please join us at</p>
						<p class="fancyText">{{ venue_name }}</p>
						<!-- <p class="fancyText">{{ venue_address }}</p> -->
					</div>
					<div style="display: flex; justify-content: center; margin-top: 10px;">
						<button style="display: flex; flex-wrap: wrap !important; align-content: center; align-items: center;" class="btn btn-light btn-lg toEventInfo fancyText" id="toEventInfoButton">
							<span style="display: flex; padding-right: 5px;" class="material-symbols-outlined">
								info
								</span>
								<div>Event Details</div>
						</button>
						
					</div>
				</div>
			</div>
			<div class="sectionDivider"></div>
			<div class="d-flex flex-column align-items-center px-4">
			<div class="imgDivider">
				<img src="https://i.imgur.com/bJ0ZU1o.png">
			</div>
				<p class="fancyText">
					Kindly reply by <br> {{ reply_deadline }}
				</p>
			</div>

			{% if past_rsvp %}
			<div class="fancyText" style="display: flex; justify-content: center; text-decoration: underline;">
				RSVPs for this event have closed.
			</div>
			{% else %}
			<div class="d-flex flex-column align-items-center submitContainer">
					<button class="btn btn-light btn-lg toRSVP fancyText toRSVPLink" id="toRSVPButton">RSVP</button>
			</div>
			{% endif %}

		</div>

	</div>

	<div>

		{% include "InvitationManager/footer.html" %}
	</div>
	</div>
	<script>
		const toRSVPButton = document.getElementById('toRSVPButton');
		if (toRSVPButton) {
			toRSVPButton.addEventListener('click', () => {
				window.location.href = "{% url 'InvitationManager:rsvp' invitation_url_id %}";
			});
		}
		const toEventInfoButton = document.getElementById('toEventInfoButton');
		if (toEventInfoButton) {
			toEventInfoButton.addEventListener('click', () => {
				window.location.href = "{% url 'InvitationManager:info' %}";
			});
		}
	</script>
</body>

</html>